react-react1-week1
Hanouj/hyf-homework pull request #22
Opened 2022-09-30 11:01 UTC by Hanouj

2022-09-30 15:52 UTC, annamourasobral requested changes
Hey, @Hanouj 
Your app is working but needs some improvement.
I really missed the styling here, we are front-end developers! 
Happy coding! 👩🏻‍💻

2022-09-30 15:52 UTC, annamourasobral commented on react/react1/week1/react1week1/src/TodoList.jsx
> +        {todoList.map((item) => <TodoListItems descp={item.description} date={item.deadLineDate} key={item.id}/> )}
those props aren't relevant here, use them inside the component

```suggestion
        {todoList.map((item) => <TodoListItems item={item} key={item.id}/> )}
```

2022-10-01 14:57 UTC, annamourasobral approved these changes
Thank you for the updates =)

2022-10-02 18:12 UTC, Hailegebriel22 reviewed
@Hanouj  Good Job. You already have received feedback from @annamourasobral, I have added a comment I hope it will be helpful.

2022-10-02 18:12 UTC, Hailegebriel22 commented on react/react1/week1/react1week1/src/Page.jsx
> +import Header from "./Header"
again it would be nice to start with `import React from 'react';`

2022-10-04 19:39 UTC, merged