react2-week1
Hanouj/hyf-homework pull request #25
Opened 2022-10-28 14:07 UTC by Hanouj

2022-10-29 15:03 UTC, Hailegebriel22 reviewed
@Hanouj  You did a great job. I leave some comments hoping that they would be helpful.

2022-10-29 15:45 UTC, Hanouj commented on react/react2/week1/react2-week1/src/SearchUser.jsx
> +          setError("Error Slow down!");
I thought about that, how can I use its own response error ?

2022-10-29 15:45 UTC, Hanouj commented on react/react2/week1/react2-week1/src/SearchUser.jsx
> +          console.log(data.items);
I will remove it ☺️ thanks

2022-10-29 15:46 UTC, Hanouj commented on react/react2/week1/react2-week1/src/RenderUser.jsx
> +        <div key={index}>
Yes you right

2022-10-31 17:41 UTC, annamourasobral requested changes
Good job, @Hanouj, you are a star! 
You can just implement @Hailegebriel22 ' suggestion and go forward to merge.
Happy coding! 👩🏻‍💻

2022-10-31 17:41 UTC, annamourasobral commented on react/react2/week1/react2-week1/src/SearchUser.jsx
> +          setError("Error Slow down!");
Thank you, @Hailegebriel22 for the input! 
You can use the response error of try/catch, @Hanouj 
This gives you a more specific kind of error.

2022-11-01 22:31 UTC, merged